### ISSUE TITLE
How to convert other type cells from .swc files

### ISSUE THREAD

**Issue by zhaolun7** [CNS-OIST/SWCTetMesher#4]
I think this repo should be a common tool to convert from .swc file to .mesh file, not only for purkinje cells.
I tried some other files , for example, https://neuromorpho.org/neuron_info.jsp?neuron_name=sc147_e2216_1
![image](https://github.com/CNS-OIST/SWCTetMesher/assets/16096787/371a5458-198b-4674-808a-9d3c626e817f)
![image](https://github.com/CNS-OIST/SWCTetMesher/assets/16096787/1b74defe-18e5-4f32-925e-949c4d2c838e)
 I don't find any error output, so I could think it runs normally.
but I think the size of output file is not like that of purkinje, which looks like bigger than origin .swc file:
![image](https://github.com/CNS-OIST/SWCTetMesher/assets/16096787/d9ef1965-de64-4e20-be42-763b0749e87b)
and I tried to use Gmsh to import the output file, `sc147_e2216_10.CNG.mesh`, it looks like:
![image](https://github.com/CNS-OIST/SWCTetMesher/assets/16096787/ed885811-74b6-44cb-b795-6292cf23f961)
I am not sure if the data meets the requirements of this repo.

**Comment by zhaolun7** [comment]
well, is there any other tools to convert .swc or could STEPS read .swc file directly ?

**Comment by WeiliangChenOIST** [comment]
Dear @zhaolun7 ,

This usually means the default mesh resolution is not sufficient for the reconstruction. You can adjust the parameters of the mesher to suit the data.

To check available parameters, use 
```
./SWCTetMesher -h
```

The most important ones are 

- fc-size
- fc-distance
- cc-size

You can find their definition in [https://doc.cgal.org/latest/Mesh_3/index.html#Mesh_3TheMeshingCriteria](https://doc.cgal.org/latest/Mesh_3/index.html#Mesh_3TheMeshingCriteria)

For your mesh, I found using ` --fc-size 0.05  --fc-distance 0.01 --cc-size 0.2` yields an ok-ish mesh, but if you want a more smooth surface you will need an even finer resolution.

**Comment by zhaolun7** [comment]
@WeiliangChenOIST  Thanks for reply. It did solve my problem.
